import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-bonded-warehouse-duty-deferral-control",
  "engine": "recovery",
  "title": "Bonded Warehouse Duty Deferral Control",
  "shortTitle": "Bonded Warehouse Duty Deferral Control",
  "tagline": "Protect duty deferral and prevent leakage through inventory, withdrawal, export, destruction, and bond reconciliation.",
  "industry": "Customs Financial Operations",
  "buyer": "Importers and bonded-warehouse operators",
  "uiPort": 4685,
  "apiPort": 5685,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Bonded Warehouse Duty Deferral Control converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports in one accountable workflow. Protect duty deferral and prevent leakage through inventory, withdrawal, export, destruction, and bond reconciliation.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Bonded Warehouse Duty Deferral Control evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("bonded-facility-registry","BWD01","Bonded facility registry","Execute bonded facility registry using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed bonded facility registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Bonded facility registry Reference","text","BWD01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("warehouse-entry-ingestion","BWD02","Warehouse entry ingestion","Execute warehouse entry ingestion using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed warehouse entry ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Warehouse entry ingestion Reference","text","BWD02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("inventory-receipt-control","BWD03","Inventory receipt control","Execute inventory receipt control using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed inventory receipt control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Inventory receipt control Reference","text","BWD03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("lot-serial-traceability","BWD04","Lot serial traceability","Execute lot serial traceability using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed lot serial traceability decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Lot serial traceability Reference","text","BWD04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("manipulation-tracking","BWD05","Manipulation tracking","Execute manipulation tracking using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed manipulation tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Manipulation tracking Reference","text","BWD05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("withdrawal-for-consumption","BWD06","Withdrawal for consumption","Execute withdrawal for consumption using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed withdrawal for consumption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Withdrawal for consumption Reference","text","BWD06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("export-withdrawal-control","BWD07","Export withdrawal control","Execute export withdrawal control using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed export withdrawal control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Export withdrawal control Reference","text","BWD07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("destruction-evidence","BWD08","Destruction evidence","Execute destruction evidence using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed destruction evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Destruction evidence Reference","text","BWD08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("five-year-deadline-monitoring","BWD09","Five-year deadline monitoring","Execute five-year deadline monitoring using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed five-year deadline monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Five-year deadline monitoring Reference","text","BWD09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("duty-liability-calculation","BWD10","Duty liability calculation","Execute duty liability calculation using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed duty liability calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Duty liability calculation Reference","text","BWD10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("bond-sufficiency-monitoring","BWD11","Bond sufficiency monitoring","Execute bond sufficiency monitoring using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed bond sufficiency monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Bond sufficiency monitoring Reference","text","BWD11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("cbp-report-reconciliation","BWD12","CBP report reconciliation","Execute cbp report reconciliation using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed cbp report reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","CBP report reconciliation Reference","text","BWD12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("inventory-discrepancy-workflow","BWD13","Inventory discrepancy workflow","Execute inventory discrepancy workflow using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed inventory discrepancy workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Inventory discrepancy workflow Reference","text","BWD13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("duty-payment-reconciliation","BWD14","Duty payment reconciliation","Execute duty payment reconciliation using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed duty payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Duty payment reconciliation Reference","text","BWD14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]}),
feature("facility-inventory-analytics","BWD15","Facility inventory analytics","Execute facility inventory analytics using warehouse entries, inventory receipts, manipulations, withdrawals, exports, destructions, duties, bond limits, deadlines, and CBP reports.","Produce a governed facility inventory analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Warehouse / Bonded Inventory","text","Warehouse / Bonded Inventory · Standard Case"],["caseReference","Facility inventory analytics Reference","text","BWD15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1085000],["supportedAmount","Evidence-Supported Amount","currency",911400],["domainDriver","Disposition","select","Consumption entry",["Consumption entry","Export","Destruction"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Bonded facility registry case","Warehouse entry ingestion case","Inventory receipt control case","Lot serial traceability case","Manipulation tracking case"]})
]);
